### PR TITLE
Python 3,unichr not defined in util.py error

### LINKED ISSUE #161: Python 3,unichr not defined in util.py error
image
in util.py line no 18 , unichr is not defined error is coming when I am using pyxform in my plugin in QGIS 3 (i.e python 3 environment)

### PR DESCRIPTION
**Pull request by yjacolin**
Fix #161

### CODE REVIEW

**Comment by ukanga** [comment]
This change breaks the current functionality as the failing tests in one python2.7 version indicates. I would expect for python 3.6 the code to be executed will be in the except clause https://github.com/XLSForm/pyxform/blob/master/pyxform/utils.py#L11 which does exactly as the change you are proposing. I suspect there maybe something else that does inject `unicode()` in your version of python 3.6 ans as such ends up in the else clause. That should be looked into on your end. Otherwise, this is a braking change that we should not accept.

**Comment by ukanga** [comment]
See https://github.com/XLSForm/pyxform/pull/164#issuecomment-354723090

I will suggest you test this on the python terminal in isolation and see if the similar error occurs.
```python
>>> from pyxform.utils import unichr
>>> unichr(10000)
```

**Comment by ukanga** [comment]
Addressed by #179.

**Comment by shivareddyiirs** [comment]
@ukanga 
Thanks. I have another request to make new release of pyxform.

**Pull request closed without merging**
