### PR TITLE
Add test for enclosed-area() function

### PR DESCRIPTION
**Pull request by ukanga**
Do not merge yet: non standard ODK Validate jar.

### CODE REVIEW

**Comment by MartijnR** [comment]
I believe this can be closed. (area() was added to public JavaRosa and ODK Validate)

**Comment by pld** [comment]
Does the JAR version in pyxform need to be upgraded?

**Comment by pld** [comment]
Was it already?

**Comment by MartijnR** [comment]
Not sure actually. I can't tell from the ODK Validate history in which commit it was added. However, both the XLSForm Offline Desktop App and http://opendatakit.org/xiframe support the area() function.

**Comment by MartijnR** [comment]
pyxform in KoBo doesn't so that makes it a bit suspicious.

**Comment by ukanga** [comment]
The jar version is at 1.4.6, so it may not need to be upgraded. Will rebase and see what changes if any need to be applied.

**Comment by ukanga** [comment]
I dropped the custom jar and rebased with master, tests are passing.

**Pull request merged**
