### PR TITLE
#292 Resolve field references upload question

### PR DESCRIPTION
**Pull request by tedrick**
Address #292 by processing field references in upload question.
Establishes tests for upload (image, audio, file) question types

### CODE REVIEW

**Comment by tedrick** [comment]
It looks like the circleci framework was non-functional when I submitted updates.  Should I add an additional commit or can the tests be re-run?

**Comment by lognaturel** [comment]
I think you should be able to re-run workflows by clicking on "Details" while logged in to GitHub and then "Rerun workflow" on CircleCI. I've done it just in case it's maintainer-only.

**Comment by tedrick** [comment]
Thanks, it appeared to maintainer-only (the button to re-run was disabled for me).

**Comment by lognaturel** [comment]
@ukanga This looks good and very low-risk to me. Giving you a chance to look so you know what the change is.

**Pull request merged**
