### PR TITLE
Report the choice name in the JSON

### PR DESCRIPTION
**Pull request by qlands**
The current JSON output does not contain the list name for "normal" select_one or select_multiple variables. It is useful to have it specially if one wants to construct a data dictionary.

I used the same key ("query") as is already used by "select one external" types.

### CODE REVIEW

**Comment by lognaturel** [comment]
The `query` concept is introduced by the select one external feature and is not actually part of [the form spec](https://opendatakit.github.io/xforms-spec/0 so I don't think it makes sense as an attribute name here.

I think `list_name` would be more appropriate.

I don't work on any tools that use the JSON representation. @jnm, you do, right? I think it's generally in an odd state and would be worth some cleanup if folks are depending on it.

**Comment by qlands** [comment]
Hi,

We use the JSON output extensively in our applications through [ODK Tools](https://github.com/qlands/odktools) which convert an ODK Excel Survey file into a MySQL database. The list name is used to create a child look-up table with the options that then is linked to the parent data-table. The list_name is important because we use it to name the look-up table.

I don't know who is the maintainer of the JSON part of pyxform but I would be happy to contribute if it does not have a patron.

I will upload the change to the PR soon.

**Comment by lognaturel** [comment]
Thanks for that extra context, @qlands. I understand why in your case you'd want to represent the choice list once even though in the corresponding XForm it would be copied for each question that uses it. What I might do in that case is use a hash of the `children` to name the table. Could that possibly work for you?

In https://github.com/XLSForm/pyxform/issues/203, I ask why static choice lists are ever generated. Another possible resolution to your issue would be to always generate secondary instances for choice lists since those do have names (accessible through `itemset`).

Because there is no concept corresponding to `list_name` in the XForm representation, I'm still not very comfortable with this but I'd like @jnm or @ukanga to chime in.

**Comment by qlands** [comment]
I could generate a hash as name but such name will not correspond to anything in the XLS form. 

Secondary instances generate "itemset" or "query" however I cannot force users to a particular format for select. I understand that list_name is not part of XForm however I'm not asking to change the XForm representation just the JSON by adding the list name. 

On other note: I ran black on my files....where can I check which file went without black?

**Comment by qlands** [comment]
Sorry people... I messes up with this PR. I will open other one cleaner without so many reverts!!!

**Comment by qlands** [comment]
We can continue the discussion in #357 . Thanks.

**Pull request closed without merging**
