### PR TITLE
Use "data" as Default Node Name

### PR DESCRIPTION
**Pull request by moshthepitt**
Implement use of "data" as root node name that one can optionally override.

Ensure existing tests do not break by having them use a custom node name as expected in each test.

Fix: #130

### CODE REVIEW

**Comment by lognaturel** [comment]
I remember @ukanga saying something about why this hadn't been merged but now I can't remember. Maybe because it's risky? It would be helpful to get a reminder of what's blocking it because I do agree it would be a wonderful change.

**Comment by ukanga** [comment]
@moshthepitt can you rebase this with the latest master so that we can give this another shot at merging it?

**Comment by moshthepitt** [comment]
@ukanga will do

**Comment by lognaturel** [comment]
Would it help if I could arrange for some manual QA on this change? Please let us know what can be done to move this forward! More users have been exploring advanced uses of XPath recently and it would be much easier if the document root name were stable rather than being based on the spreadsheet filename.

**Comment by moshthepitt** [comment]
@ukanga @lognaturel let me try to rebase this by the end of the week then we can take stock on where we are.  Sounds good?

**Comment by jkpr** [comment]
As I wrote over at #335, 

I was looking through the code for the XML root / default node name. I don't know why I missed it before. In the settings, I can simply use `name` as a key and then set the value to what I would like, such as `LS` in my example above.

In the conversations at #130 and #152, I do not see conversation about this setting, so maybe everyone knows about it. One way fix #152 would be to set the `name` key to `data` in the settings tab. This isn't published on xlsform.org, though.

**Comment by yanokwa** [comment]
@ukanga was uncomfortable with the existing solution and now it's very out of date. Closing in favor with #368.

**Pull request closed without merging**
