### PR TITLE
Performance regression fix on using relative paths

### LINKED ISSUE #247: Performance regression in 0.12
xls2xform 0.12.0 takes *a lot* longer to convert to XML than 0.11.5.  

I noticed this problem on [this forum topic](https://forum.opendatakit.org/t/502-bad-gateway-error-while-using-the-xlsform-online/16866) and to investigate, I set up a local [xlsform-server](https://github.com/opendatakit/xlsform-server) and used the [soar.xlsx.zip form](https://github.com/XLSForm/pyxform/files/2717811/soar.xlsx.zip).

I then ran a local conversion
```
cd /home/ubuntu/xlsform/xlsform_env/bin/
time ./xls2xform /home/vagrant/test.xlsx /tmp/test.xml
```

On pyxform 0.11.5, it took about 1.4 seconds (multiple runs)
On pyxform 0.12.0, it took about 23 seconds (multiple runs)

On a very fast local machine, this change isn't that noticeable (it takes 2 seconds), but on a single-core cloud VPS like the one that runs http://opendatakit.org/xlsform, it pegs the CPU for minutes at a time and results in gateway timeouts.

My guess is that this regression happened with https://github.com/XLSForm/pyxform/pull/187.

@MartijnR @ukanga can you reproduce?

### PR DESCRIPTION
**Pull request by ukanga**
Cuts down performance hit introduced by the relative path functionality. We still get an additional 1 second in my test environment between v0.11.5 and this PR's branch, which is way better than the 38s+ introduced in v0.12.0.

```shell
for ((i=0; i<10; i++)); do time xls2xform /tmp/soar.xlsx /tmp/soar.xml > /dev/null; done
```
This branch has the following times on my test environment:
```shell
real    0m3.136s	user    0m5.228s	sys     0m0.124s
real    0m3.225s	user    0m5.224s	sys     0m0.208s
real    0m3.247s	user    0m5.448s	sys     0m0.184s
real    0m3.184s	user    0m5.124s	sys     0m0.144s
real    0m3.206s	user    0m5.168s	sys     0m0.156s
real    0m3.185s	user    0m5.232s	sys     0m0.176s
real    0m3.175s	user    0m5.076s	sys     0m0.152s
real    0m3.528s	user    0m5.696s	sys     0m0.172s
real    0m3.302s	user    0m5.388s	sys     0m0.156s
real    0m3.312s	user    0m5.420s	sys     0m0.156s
```

v0.11.5 has:
```shell
real    0m2.294s	user    0m4.300s	sys     0m0.140s
real    0m2.184s	user    0m3.928s	sys     0m0.164s
real    0m2.247s	user    0m4.104s	sys     0m0.164s
real    0m2.287s	user    0m4.296s	sys     0m0.148s
real    0m2.300s	user    0m4.240s	sys     0m0.136s
real    0m2.227s	user    0m4.220s	sys     0m0.148s
real    0m2.346s	user    0m4.580s	sys     0m0.132s
real    0m2.378s	user    0m4.500s	sys     0m0.160s
real    0m2.617s	user    0m4.720s	sys     0m0.180s
real    0m2.350s	user    0m4.440s	sys     0m0.144s
```

v0.12.0 has:
```shell
real    0m40.083s	user    0m42.208s	sys     0m0.168s
real    0m45.988s	user    0m47.340s	sys     0m0.232s
real    0m41.181s	user    0m43.160s	sys     0m0.212s
real    0m40.310s	user    0m42.412s	sys     0m0.160s
real    0m40.561s	user    0m42.572s	sys     0m0.176s
real    0m41.495s	user    0m43.396s	sys     0m0.176s
real    0m42.968s	user    0m45.012s	sys     0m0.200s
real    0m39.686s	user    0m41.640s	sys     0m0.184s
real    0m40.599s	user    0m42.576s	sys     0m0.236s
real    0m39.867s	user    0m41.820s	sys     0m0.144s
```

Fix #247

### CODE REVIEW

**Comment by yanokwa** [comment]
Thanks for the quick turnaround on this, @ukanga. If you need a beefier form to test with, [HHS_FORM.xlsx](https://github.com/XLSForm/pyxform/files/2725642/HHS_FORM.xlsx) is good too.

**Comment by ukanga** [comment]
@yanokwa Does relative referencing not apply to `indexed-repeat()` parameters? I am getting the exception below for the form [HHS_FORM.xlsx](https://github.com/XLSForm/pyxform/files/2725642/HHS_FORM.xlsx).
```java
java.lang.RuntimeException: Error evaluating field 'p1': The problem was located in calculate expression for /HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/p1
XPath evaluation: type mismatch
indexed-repeat(): parameter 2 must be a parent of the field in parameter 1
```
The current release is generating the XML:
```XML
<bind calculate="indexed-repeat( /HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/ros3/q38 ,  ../ros3 , 1)" nodeset="/HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/p1" type
      ="string"/>
```
Should it always be?
```XML
<bind calculate="indexed-repeat( /HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/ros3/q38 ,  /HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/ros3 , 1)" nodeset="/HHS_FORM/g4/ts/cu5/u5_sick/g15/g16/g18/p1" type
      ="string"/>
```

@MartijnR Any thoughts on the above?

**Comment by MartijnR** [comment]
Good discovery about indexed-repeat(). I think paths within parameters of this function are best excluded from the relative path feature, since indices are part of this function. So that would keep your second XML output.

I think one of the reasons indexed-repeat() was invented was because of the lack of relative path support in pyxform output. In my opinion it's a very awkward function (especially on the XForm side actually). Now that we have relative paths, I think we might want to start thinking about additional pyxform features to create a better non-xpath-function alternative for the remaining use cases that convert directly into native XPath, using ${node}, ${repeat} and [position].

**Comment by KeynesYouDigIt** [comment]
Im pretty new to xpath so pardon my ignorance - "would a repeat" be a shared piece of the path or represent the same path entirely? Whats a good resource to get more familiar with XML/Xpath? I know what they are but not in great depth

**Pull request merged**
