### PR TITLE
Upload Question - resolve field references

### PR DESCRIPTION
**Pull request by tedrick**
This addresses #292 and adds XPath insertion to upload type questions.

### CODE REVIEW

**Comment by tedrick** [comment]
@ukanga - I've updated the attribute column test (as this is adding an attribute) to check for the intended output (this also had the side effect of testing external namespace addition as well)

**Comment by ukanga** [comment]
@tedrick It is expected that any new test addition should use the markdown approach, I was expecting this change in tests_v1 rather than an updated excel XLSForm file.

**Comment by lognaturel** [comment]
@tedrick making sure you saw @ukanga's ask to put the test in the `tests_v1` format! Please ask if you have any questions.

**Comment by tedrick** [comment]
Yes, it's in my backlog - it's been a busy summer :)

**Comment by lognaturel** [comment]
Thanks for the status update, @tedrick! 🎉 Here's to a less busy fall for all of us!

**Comment by tedrick** [comment]
Closing in favor of #386

**Pull request closed without merging**
