### PR TITLE
Remove badges for unused services

### PR DESCRIPTION
**Pull request by lognaturel**
Updates readme to reflect services currently in use.

### CODE REVIEW

**Comment by lognaturel** [comment]
I was hoping that this would give a clean commit we could use to get the build green again since I forgot to disable the AppVeyor and CircleCI webhooks before the last merge. However, AppVeyor tasks are still running for reasons I don't understand. Anyone else know what needs to be done to disable AppVeyor entirely?

**Comment by lindsay-stevens** [comment]
Maybe this was already done, and I can't see the Settings tab for this repo, but there should be a Webhooks section where they can be deleted (example screenshot below).

image

Failing that, the Appveyor config points to https://ci.appveyor.com/project/ukanga/pyxform so maybe @ukanga could delete (or disable) the pyxform project there?

Also there's the profile-level (or XLSForm org-level) OAuth privileges which may still be allowing Appveyor to run checks (example screenshot below)

image

**Review by lindsay-stevens — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @lindsay-stevens! I've disabled the webhooks and that worked for CircleCI. I don't have org-level admin access so I can't see the screen you captured. Could you please revoke AppVeyor and CircleCI access?

**Comment by lindsay-stevens** [comment]
@lognaturel oh I meant the example OAuth screenshot is from my personal profile, and my guess is there is something similar for orgs. I am a member of the XLSForm org but probably only an "owner" member can do this sort of thing. I think we will need assistance from @ukanga on this one.

**Comment by lognaturel** [comment]
Aha! @yanokwa was able to remove the application at the org level. Thanks for the tip, @lindsay-stevens.

**Pull request merged**
