### PR TITLE
Add xforms version

### LINKED ISSUE #393: Output `no-repeat-reference-error` in some manner or the pyxform version or the xforms version
For discussion. 

Some advanced XPath enthusiasts (@ln) are running into issues caused by Enketo's workaround for a major XForm syntax issue: https://opendatakit.github.io/xforms-spec/#a-big-deviation-with-xforms.

Pyxform recently started generating relative repeat node references, so we're on the verge of  being able to [remove this nasty deviation](https://github.com/opendatakit/xforms-spec/issues/251) from the ODK XForms spec (I think). 

However, since we still need to be able to run forms that were transformed by older versions of pyxform, it will be many years before we can remove the code workarounds in Enketo and Collect. This means it is a challenge, for Enketo, to facilitate support for those very cool advanced forms.

This may be a good reason to add some versioning or featuring in the XForms output. E.g. the output could contain a `no-repeat-reference-error` class or a `pyxform-version` attribute. Data collection clients could disable the bug-causing workaround for the buggy XForms syntax based on the presence of this class or the value of the attribute.

I imagine there will be more valid use cases in the future, so perhaps a version attribute is the easiest?

### PR DESCRIPTION
**Pull request by MartijnR**
closes #393

### CODE REVIEW

**Comment by MartijnR** [comment]
@lognaturel, there is [one pesky test](https://github.com/XLSForm/pyxform/blob/master/pyxform/tests/xform2json_test.py#L45) that outputs `odk:xforms-version=""` instead of `odk:xforms-version="1.0.0"`. Do you perhaps have an idea to could put me in the right direction to fix this?

**Comment by lognaturel** [comment]
Taking a look now! Those XForm2json tests are really frustrating. Do you know of anyone using that code to attempt to parse XForms to get JSON?

**Comment by lognaturel** [comment]
At a high-level, I imagine that `xform2json.py` needs to explicitly save the value of that attribute when it parses an XForm. You probably figured that. Digging deeper...

**Comment by lognaturel** [comment]
https://github.com/lognaturel/pyxform/commit/f392273ca9cdd7c43fb8bc854c288c6f56d2c188 is a fix.

**Comment by MartijnR** [comment]
Thank you so much!

Sorry, I messed up the branch. Indeed, it shouldn't be an XLSForm setting!

**Comment by MartijnR** [comment]
Thank you! Turned out to be just a simple change, but it got me to explore the exciting  world of pyxform. Ready for my next assignment! (No, I'm joking, I need a lengthy rest first!)

**Comment by lognaturel** [comment]
> I need a lengthy rest first!

`pyxform` makes me feel like that a lot, too. It's definitely a heavy thing maintaining old code bases when the original masterminds aren't around. But everything we do here adds a lot of value to users so that keeps me going.

**Pull request merged**
