### PR TITLE
Add ODK Validate 1.5.0 jar.

### LINKED ISSUE #114: Use Validate 1.5.0
JavaRosa [has added some XPath functions and `range`](https://github.com/opendatakit/javarosa/releases/tag/v2.2.0). Validate was updated to [v1.5.0](https://github.com/opendatakit/validate/releases/tag/v1.5.0).

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #114. Confirmed working on macOS, Linux and Windows 10.

<strike>I have verified that I can run this jar from where it is with `java -jar ODK_Validate.jar`. The UI shows the version as 1.5.0 and a form such as [contains_starts-with_ends-with.txt](https://github.com/XLSForm/pyxform/files/1042485/contains_starts-with_ends-with.txt) that uses new XPath functions validates. I can also run Validate through the CLI and get the same results.

However, if I run `python ./xls2xform.py` on the corresponding XLSForm -
[contains_starts-with_ends-with.xlsx](https://github.com/XLSForm/pyxform/files/1042489/contains_starts-with_ends-with.xlsx) - I get the same ODK Validate errors as I got with the old jar. Interestingly, if I then run this same jar on the resulting xml file, it validates as expected.

When I run `nosetests`, I get the same behavior as on master. 117 passes but there is `usage: nosetests [-h] [--json] [--skip_validate] path_to_XLSForm output_path nosetests: error: too few arguments` printed part way through.

Is there something special that needs to be done to update the jar? Paging @lindsay-stevens because I see you were the last to do this update and had to fix some previous issues.</strike>

### CODE REVIEW

**Comment by lognaturel** [comment]
The problem was that because I had already installed `pyxform` through `pip`, that was being used. Now I've uninstalled through `pip` and when I run `python pyxform/xls2xform.py path_to_XLSForm output_path` as recommended by the README, I get 
```
  File "pyxform/xls2xform.py", line 7, in <module>
    from pyxform import xls2json, builder
ImportError: No module named pyxform
```
I'm not very familiar with running scripts in modules in this way. What's the right approach?

**Comment by lindsay-stevens** [comment]
I don't know if this is the same issue. My notes on the jar are in
pyxform/#63. To see what I mean there, compare the archive structure of the
146 jar to the previous. In my fork of Validate, there is an AppVeyor build
script + other updates, to show how the jar I pushed to pyxform was built.

On 1 Jun. 2017 8:26 am, "Hélène Martin" <notifications@github.com> wrote:

The problem was that because I had already installed pyxform through pip,
that was being used. Now I've uninstalled through pip and when I run python
pyxform/xls2xform.py path_to_XLSForm output_path as recommended by the
README, I get

  File "pyxform/xls2xform.py", line 7, in <module>
    from pyxform import xls2json, builder
ImportError: No module named pyxform

I'm not very familiar with running scripts in modules in this way. What's
the right approach?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/XLSForm/pyxform/pull/116#issuecomment-305335920>, or mute
the thread

**Comment by lognaturel** [comment]
Thank you, @lindsay-stevens! That extra background is very helpful and it's good to know I should verify this on Windows.

My broader problem now is just that I can't figure out how to run `xls2xform.py` 😖. Any advice on that appreciated.

**Comment by lindsay-stevens** [comment]
Did you try using the module arg? E.g.

python -m pyxform/xls2xform path

See https://docs.python.org/3/using/cmdline.html

**Comment by dorey** [comment]
@lognaturel , to run local code, you should uninstall the `pip` installed version  (`pip uninstall pyxform`) because it probably pulled the source from pypi. Then, assuming you're running inside a [`virtualenv`](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/) with the [virtualenvwrapper helper](https://virtualenvwrapper.readthedocs.io/en/latest/), you can get set up as simply as:

```
mkvirtualenv local_pyxform # or whatever you want to name it
(local_pyxform)$ python setup.py develop
(local_pyxform)$ python pyxform/xls2xform.py --help
(local_pyxform)$ xls2xform --help
```

That last shortcut is available because of the [entry point](https://github.com/lognaturel/pyxform/blob/7479d0d3b545ac80b84b3ff5b8fd0a4296b2a3d8/setup.py#L31) in `setup.py`.

And later, you can leave the virtualenv with `deactivate` and get back in with `workon local_pyxform`
```
(local_pyxform)$ deactivate
$ xls2xform --help 
# -bash: xls2xform: command not found
$ workon local_pyxform
(local_pyxform)$ which xls2xform # prove we can access the scripts again
~/.virtualenvs/local_pyxform/bin/xls2xform
```

**Comment by lognaturel** [comment]
Thank you @dorey, @lindsay-stevens. I'll update the readme.

I can confirm that this updated jar works with OS X and Linux. Does one of you have a Windows machine/VM handy that you could quickly verify on?

**Comment by dorey** [comment]
Question for @lognaturel: What process went into making this `ODK Validate.jar`? Did you make changes or recompile the JAR?

I ask because it would be nice if we could either verify a checksum with a trusted source or compile the JAR locally when the package is installed so that we don't have to approve or disapprove binary files from new contributors.

(also, no access to a windows VM here. sorry!)

**Comment by lognaturel** [comment]
Good idea, @dorey! This is the jar that is now available [on the ODK website](https://opendatakit.org/downloads/download-info/odk-validate-2/) and there's a checksum there you should be able to verify. 

If this doesn't work on Windows, we should figure out what needs to be changed in the packaging process and document it on the Validate side so that we can always use the official jar.

**Comment by lindsay-stevens** [comment]
I suggest using AppVeyor. It's Travis, but for Windows. Here's an example
config, to run a test suite and build a pyinstaller exe.

https://github.com/lindsay-stevens/odk_tools/blob/master/appveyor.yml

That repo/project was the reason for my pyxform PR so it might be
interesting to browse otherwise.

**Comment by lognaturel** [comment]
I'll investigate getting set up AppVeyor. In the mean time, I have verified that this works with Windows 10, Python 2.7.13. If we think that's a sufficient verification, it should be ready to merge.

**Comment by ukanga** [comment]
Cool, I have created an issue for Appveyor https://github.com/XLSForm/pyxform/issues/124, might take a stub later today since I linked the repo with the CI already.

**Pull request merged**
